#! /bin/sh

set -f
set -- $SSH_ORIGINAL_COMMAND

PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH

SFTP_COMMAND=$(cat /run/sshd/sftp_command)

case "$1" in
  knotc|"$SFTP_COMMAND")
    exec "$@"
    ;;
  *)
    echo "Command not permitted" 1>&2
    exit 1
    ;;
esac
